// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBm9S37LaYcppZ5gOxiUX1fSW5xon0O8T4',
    appId: '1:566599363327:web:ae50bec2708440be943aca',
    messagingSenderId: '566599363327',
    projectId: 'sports-ticketing-d8193',
    authDomain: 'sports-ticketing-d8193.firebaseapp.com',
    storageBucket: 'sports-ticketing-d8193.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCizcJsG7HLpA0cSjb8YDuabQmPCDxEdRg',
    appId: '1:566599363327:android:36886c15d2233c30943aca',
    messagingSenderId: '566599363327',
    projectId: 'sports-ticketing-d8193',
    storageBucket: 'sports-ticketing-d8193.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAi2zZ8GeNTs5UCwck9RRXhmU6wLLp09U4',
    appId: '1:566599363327:ios:5ad45a450990152a943aca',
    messagingSenderId: '566599363327',
    projectId: 'sports-ticketing-d8193',
    storageBucket: 'sports-ticketing-d8193.firebasestorage.app',
    iosBundleId: 'com.example.sportTicketing',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAi2zZ8GeNTs5UCwck9RRXhmU6wLLp09U4',
    appId: '1:566599363327:ios:5ad45a450990152a943aca',
    messagingSenderId: '566599363327',
    projectId: 'sports-ticketing-d8193',
    storageBucket: 'sports-ticketing-d8193.firebasestorage.app',
    iosBundleId: 'com.example.sportTicketing',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBm9S37LaYcppZ5gOxiUX1fSW5xon0O8T4',
    appId: '1:566599363327:web:a062c1cb8193901d943aca',
    messagingSenderId: '566599363327',
    projectId: 'sports-ticketing-d8193',
    authDomain: 'sports-ticketing-d8193.firebaseapp.com',
    storageBucket: 'sports-ticketing-d8193.firebasestorage.app',
  );

}